name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Tự động publish khi push tag vX.X.X

permissions:
  id-token: write  # Cho phép dùng OIDC để publish qua Trusted Publisher
  contents: read

jobs:
  publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI (Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true  # ❌ Gỡ nếu không cần ký số để tăng tốc
          #skip-existing: true   # ✅ Không fail nếu gói đã tồn tại (an toàn hơn)
